const mongoose=require('mongoose');
const problemschema=new mongoose.Schema({
    title:{
        type:String,
        required:true,
        minLength:6,
        maxLength:50
    },
    description:{
        type:String,
        required:true
    },
    difficulty:{
        type:String,
        enum:["Easy","Medium","Hard"],
        required:true
    },
    tags:{
        type:String,
         required:true,
    },
    visibletestcases:[{
        input:{
            type:String,
            required:true
        },
        output:{
            type:String,
            required:true
        },
        explanation:{
            type:String,
            required:true
        }
    }],
    hiddentestcases:[{
        input:{
            type:String,
            required:true
        },
        output:{
            type:String,
            required:true
        }
    }],
    startcode:[{
        language:{
            type:String,
        required:true
        },
        initialcode:{
            type:String,
            required:true
        }
    }],
    refsolution:[{
        language:{
            type:String,
        required:true
        },
        solution:{
            type:String,
            required:true
        }
    }],
    problemcreator:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'user',
        required:true
    }
},{
    timestamps:true
})

const Problem=mongoose.model('problem',problemschema);
module.exports=Problem;